export const h2ReservedKeywords = [
    "ALL", "AND", "ANY", "ARRAY", "AS", "ASC", "BETWEEN", "BOTH", "CASE",
    "CHECK", "COLUMN", "CONSTRAINT", "CROSS", "CURRENT_DATE", "CURRENT_TIME",
    "CURRENT_TIMESTAMP", "CURRENT_USER", "DISTINCT", "ELSE", "END", "EXCEPT",
    "EXISTS", "FALSE", "FETCH", "FOR", "FOREIGN", "FROM", "FULL", "GROUP",
    "HAVING", "IF", "IN", "INNER", "INTERSECT", "INTERSECTION", "IS", "JOIN",
    "LIKE", "LIMIT", "MINUS", "NATURAL", "NOT", "NULL", "OFFSET", "ON",
    "OR", "ORDER", "OUTER", "PRIMARY", "REFERENCES", "RIGHT", "ROWNUM",
    "SELECT", "SYSDATE", "SYSTIME", "SYSTIMESTAMP", "TABLE", "THEN", "TODAY",
    "TOP", "TRAILING", "TRUE", "UNION", "UNIQUE", "USER", "USING", "VALUES",
    "WHERE", "WITH",
];